convocatoria:
    path:     /
    defaults: { _controller: "SiviuqMainBundle:Convocatoria:index" }
    
convocatoria_investigador:
    path: /investigadores
    defaults: {_controller: "SiviuqMainBundle:Convocatoria:convocatoriasInvestigador"}

convocatoria_show:
    path:     /{id}/show
    defaults: { _controller: "SiviuqMainBundle:Convocatoria:show" }

convocatoria_new:
    path:     /new
    defaults: { _controller: "SiviuqMainBundle:Convocatoria:new" }

convocatoria_create:
    path:     /create
    defaults: { _controller: "SiviuqMainBundle:Convocatoria:create" }
    requirements: { _method: post }

convocatoria_edit:
    path:     /{id}/edit
    defaults: { _controller: "SiviuqMainBundle:Convocatoria:edit" }

convocatoria_update:
    path:     /{id}/update
    defaults: { _controller: "SiviuqMainBundle:Convocatoria:update" }
    requirements: { _method: post|put }

convocatoria_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiviuqMainBundle:Convocatoria:delete" }
    requirements: { _method: post|delete }
