proyectos:
    path:     /
    defaults: { _controller: "SiviuqMainBundle:Proyectos:index" }

proyectos_show:
    path:     /{id}/show
    defaults: { _controller: "SiviuqMainBundle:Proyectos:show" }
    
download_file: 
    pattern:  /download/{filename}
    defaults: { _controller: SiviuqMainBundle:Proyectos:download }
    
siviuq_proyectos_actualizar:
    pattern: /actualizar
    defaults: {_controller: SiviuqMainBundle:Proyectos:actualizarProyectoFacultad}

proyectos_new:
    path:     /new
    defaults: { _controller: "SiviuqMainBundle:Proyectos:new" }
    
proyectos_nuevo:
    path:     /{id}/nuevo
    defaults: { _controller: "SiviuqMainBundle:Proyectos:newProyecto" }

proyectos_create:
    path:     /create
    defaults: { _controller: "SiviuqMainBundle:Proyectos:create" }
    requirements: { _method: post }
    
proyectos_aplicar:
    path:     /aplicar/{id}
    defaults: { _controller: "SiviuqMainBundle:Proyectos:createProyecto" }
    requirements: { _method: post }

proyectos_edit:
    path:     /{id}/edit
    defaults: { _controller: "SiviuqMainBundle:Proyectos:edit" }

proyectos_update:
    path:     /{id}/update
    defaults: { _controller: "SiviuqMainBundle:Proyectos:update" }
    requirements: { _method: post|put }

proyectos_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiviuqMainBundle:Proyectos:delete" }
    requirements: { _method: post|delete }
    
proyectos_accept:
  path: /{id}/aceptar
  defaults: {_controller: "SiviuqMainBundle:Proyectos:proyectoAprobado"}

proyectos_reject:
  path: /{id}/rechazar
  defaults: {_controller: "SiviuqMainBundle:Proyectos:proyectoNoAprobado"}
  
proyectos_generate:
  path: /{id}/certificado
  defaults: {_controller: "SiviuqMainBundle:Proyectos:generarCertificado"}
  
proyectos_investigador:
  path: /Investigador
  defaults: {_controller: "SiviuqMainBundle:Proyectos:verProyectosInvestigador"}

proyectos_upload:
  path: /Investigador/Upload/{id}
  defaults: {_controller: "SiviuqMainBundle:Proyectos:subirAvance"}
  
proyectos_search:
  path: /busquedaAvanzada
  defaults: {_controller: "SiviuqMainBundle:Proyectos:busquedaAvanzadaProyectos"}

proyectos_filter: 
  path: /filtrar
  defaults: {_controller: "SiviuqMainBundle:Proyectos:buscarFiltros"}
