proyectos:
    path:     /
    defaults: { _controller: "SiviuqMainBundle:Proyectos:index" }

proyectos_show:
    path:     /{id}/show
    defaults: { _controller: "SiviuqMainBundle:Proyectos:show" }
    
download_file: 
    pattern:  /download/{filename}
    defaults: { _controller: SiviuqMainBundle:Proyectos:download }

proyectos_new:
    path:     /new
    defaults: { _controller: "SiviuqMainBundle:Proyectos:new" }

proyectos_create:
    path:     /create
    defaults: { _controller: "SiviuqMainBundle:Proyectos:create" }
    requirements: { _method: post }

proyectos_edit:
    path:     /{id}/edit
    defaults: { _controller: "SiviuqMainBundle:Proyectos:edit" }

proyectos_update:
    path:     /{id}/update
    defaults: { _controller: "SiviuqMainBundle:Proyectos:update" }
    requirements: { _method: post|put }

proyectos_delete:
    path:     /{id}/delete
    defaults: { _controller: "SiviuqMainBundle:Proyectos:delete" }
    requirements: { _method: post|delete }
