siviuq_main_homepage:
    path:     /hello/{name}
    defaults: { _controller: SiviuqMainBundle:Default:index }

siviuq_main_help:
    path:     /ayuda/{tema}
    defaults: { _controller: SiviuqMainBundle:Default:ayuda }
    
siviuq_semilleros_list:
    path: /semilleros/listar
    defaults: {_controller: SiviuqMainBundle:Semillero:findAll }
    
siviuq_semilleros_oneSemi:
    path: /semilleros/listar/{id}
    defaults: {_controller: SiviuqMainBundle:Semillero:getById }

download_route:
    pattern:  /download/{filename}
    defaults: { _controller: SiviuqMainBundle:Semillero:download }
    
requisitos_download:
    pattern: /requisitos
    defaults: {_controller: SiviuqMainBundle:Semillero:mostrar}
    
siviuq_proyectos_listar:
    pattern: /proyectos/listar
    defaults: {_controller: SiviuqMainBundle:Proyectos:mostrar}