siviuq_main_convocatoria:
    resource: "@SiviuqMainBundle/Resources/config/routing/convocatoria.yml"
    prefix:   /convocatoria

siviuq_main_proyectos:
    resource: "@SiviuqMainBundle/Resources/config/routing/proyectos.yml"
    prefix:   /proyectos    
    
