siviuq_main_gruposinvestigacion:
    resource: "@SiviuqMainBundle/Resources/config/routing/gruposinvestigacion.yml"
    prefix:   /gruposinvestigacion

siviuq_main_avance:
    resource: "@SiviuqMainBundle/Resources/config/routing/avance.yml"
    prefix:   /avance

siviuq_main_evaluador:
    resource: "@SiviuqMainBundle/Resources/config/routing/evaluador.yml"
    prefix:   /evaluador

siviuq_main_investigador:
    resource: "@SiviuqMainBundle/Resources/config/routing/investigador.yml"
    prefix:   /investigador

siviuq_main_convocatoria:
    resource: "@SiviuqMainBundle/Resources/config/routing/convocatoria.yml"
    prefix:   /convocatoria

siviuq_main_proyectos:
    resource: "@SiviuqMainBundle/Resources/config/routing/proyectos.yml"
    prefix:   /proyectos    
    
