siviuq_main_homepage:
    path:     /hello/{name}
    defaults: { _controller: SiviuqMainBundle:Default:index }

siviuq_main_help:
    path:     /ayuda/{tema}
    defaults: { _controller: SiviuqMainBundle:Default:ayuda }
    
siviuq_semilleros_list:
    path: /semilleros/listar
    defaults: {_controller: SiviuqMainBundle:Semillero:findAll }
    
siviuq_semilleros_oneSemi:
    path: /semilleros/listar/{id}
    defaults: {_controller: SiviuqMainBundle:Semillero:getById }
    
siviuq_main_addCategoria:
    path:     /categoria/add/{nombre}
    defaults: { _controller: SiviuqMainBundle:Categoria:add }
    
siviuq_main_updateCategoria:
    path:     categoria/update/{id}/{nombre}
    defaults: { _controller: SiviuqMainBundle:Categoria:update }
    
siviuq_main_deleteCategoria:
    path:     categoria/delete/{id}/
    defaults: { _controller: SiviuqMainBundle:Categoria:delete }


download_route:
    pattern:  /download/{filename}
    defaults: { _controller: SiviuqMainBundle:Semillero:download }
    
requisitos_download:
    pattern: /requisitos
    defaults: {_controller: SiviuqMainBundle:Semillero:mostrar}